# [NumPy](https://numpy.org/) Tutorial
**NumPy**'s main object is the **homogeneous** multidimensional array. It is a table of elements (usually numbers), all of the **same type**, indexed by a tuple of non-negative integers.

Cheat Sheets:
* [by DataCamp](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)
* [by DataQuest](https://s3.amazonaws.com/dq-blog-files/numpy-cheat-sheet.pdf)

## Load the package

In [ ]:
import numpy as np
# alias

### Version
`__version__`

**dunder** - Double Underscore

In [ ]:
print(np.__version__)

1.22.1


## Array
NumPy provides an N-dimensional array type, the `ndarray`, which describes a collection of "items" of the same type. The items can be indexed using for example N integers.

### Basics
[np.array()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html)

In [ ]:
a = np.array([1,2,3,4,5,6])
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [ ]:
[1,2,3]

[1, 2, 3]

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
# Ask for Help
# np.info(np.array)

#### Inspecting

In [ ]:
# Get Dimension
a.ndim

1

In [ ]:
# Get Type
a.dtype

dtype('int32')

In [ ]:
a.astype('float')

array([1., 2., 3., 4., 5., 6.])

In [ ]:
# Get number of elements
a.size

6

In [ ]:
# Get Size
a.itemsize

4

In [ ]:
# Get total size
a.nbytes

24

In [ ]:
a.shape

(6,)

In [ ]:
st_array = np.array(['a', 'b'])

In [ ]:
''.join(st_array.tolist())

'ab'

In [ ]:
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### Array Shapes
<img src="numpy-1d2d3d-array.png" style="height:300px">

In [ ]:
b = np.array([
    [9.0,8.0,7.0],
    [6.0,5.0,4.0]
])
print(b)
print(type(b))

[[9. 8. 7.]
 [6. 5. 4.]]
<class 'numpy.ndarray'>


In [ ]:
# Get Shape
b.shape

(2, 3)

In [ ]:
b.size

6

In [ ]:
c = np.array([
    [
        [1,2,3],
        [5,3,4]
    ],
    [
        [1,5,6],
        [5,7,8]]
    ]
)
print(c)
print(type(c))

[[[1 2 3]
  [5 3 4]]

 [[1 5 6]
  [5 7 8]]]
<class 'numpy.ndarray'>


In [ ]:
c.shape

(2, 2, 3)

In [ ]:
c.size

12

### Special Arrays

#### zeros()
`zeros()`

In [ ]:
# All 0s matrix
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### ones()
`ones()`

In [ ]:
# All 1s matrix
np.ones((3,2,4), dtype='int32')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

#### identity()
`identity()`

In [ ]:
# The identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### full()
`full()`

In [ ]:
# Any other number
np.full((3,4), 81)

array([[81, 81, 81, 81],
       [81, 81, 81, 81],
       [81, 81, 81, 81]])

In [ ]:
print(a)
np.full(a.shape, 5)

[1 2 3 4 5 6]


array([5, 5, 5, 5, 5, 5])

#### full_like()
`full_like()`

In [ ]:
# Any other number (full_like)
print(a)
np.full_like(a, 5)

[1 2 3 4 5 6]


array([5, 5, 5, 5, 5, 5])

#### repeat()
`repeat()`

In [ ]:
# Repeat an array
arr = np.array([
    [1,2,3]
])
print(arr.shape)
r1 = np.repeat(arr, 5, axis=0)
print(r1)

(1, 3)
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


#### linspace()
`linspace()`

In [ ]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
np.linspace(0,100,11)[1:-1]

array([10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [ ]:
np.linspace(0,100,10,endpoint=False)

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [ ]:
np.linspace(0,100,10,endpoint=False)[1:]

array([10., 20., 30., 40., 50., 60., 70., 80., 90.])

#### arange()
Like the standard **Python** function `range()`, **NumPy** has a similar function called `arange()`

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,3)

array([0, 3, 6, 9])

### Randomization

In [ ]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.79662463, 0.1438735 ],
       [0.76905587, 0.61482748],
       [0.69381196, 0.70213324],
       [0.36385285, 0.46952662]])

In [ ]:
np.random.rand(4,2)

array([[0.90115964, 0.38513049],
       [0.56532307, 0.52006066],
       [0.88066332, 0.21336385],
       [0.87994798, 0.36306446]])

In [ ]:
np.random.seed(0)
np.random.rand(4,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

In [ ]:
np.random.seed(0)
np.random.rand(4,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

In [ ]:
# Random Integer values
np.random.seed(0)
np.random.randint(-4,8, size=(5,5))

array([[ 1, -4, -1,  7, -1],
       [ 3,  5, -1,  1, -2],
       [ 0,  3,  2,  4,  4],
       [ 6, -3,  2,  3,  3],
       [ 4, -3,  1,  5,  4]])

### Copying Arrays

In [ ]:
a = np.array([1,2,3])
b = a.copy()
c = a

print("before:")
print("a", a)
print("b", b)
print("c", c)

b[0] = 100
print("after b:")
print("a", a)
print("b", b)
print("c", c)

c[0] = 10

print("after c:")
print("a", a)
print("b", b)
print("c", c)

before:
a [1 2 3]
b [1 2 3]
c [1 2 3]
after b:
a [1 2 3]
b [100   2   3]
c [1 2 3]
after c:
a [10  2  3]
b [100   2   3]
c [10  2  3]


#### .tolist()
`tolist()`

In [ ]:
print(c)
type(c.tolist())

[10  2  3]


list

## Accessing/Changing specific elements, rows, columns, etc

### Accessing

In [ ]:
l = [1,2,3,4,5]
l[1:-1]

[2, 3, 4]

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get a specific element [r, c]
a[1, 5]

13

In [ ]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [ ]:
print(a)
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


array([2, 4, 6])

### Changing

In [ ]:
print("before:\n", a)
a[1,5] = 20
print("after:\n", a)

before:
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
after:
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [ ]:
print("before:\n", a)
a[:,3] = 3
print("after:\n", a)

before:
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
after:
 [[ 1  2  3  3  5  6  7]
 [ 8  9 10  3 12 20 14]]


In [ ]:
print("before:\n", a)
a[:,2] = [1000,2000]
print("after:\n", a)

before:
 [[ 1  2  3  3  5  6  7]
 [ 8  9 10  3 12 20 14]]
after:
 [[   1    2 1000    3    5    6    7]
 [   8    9 2000    3   12   20   14]]


*3-d example

In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
print("shape:", b.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape: (2, 2, 2)


In [ ]:
# Get specific element (work outside in)
b[0,1,1]

4

In [ ]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [ ]:
# replace
print("before:\n", b)
b[:,1,:] = [[9,9],[8,8]]
print("after:\n", b)

before:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
after:
 [[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [ ]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

#### Example
Create 5x5 Array with 1s on border, 0s inside and 9 in the center
```python
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
```

In [ ]:
list1 = [12,3,4]

In [ ]:
list1[0] = -7

In [ ]:
list1

[-7, 3, 4]

In [ ]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Reorganizing Arrays

#### .reshape()
`reshape()`

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print("before")
print(before)
print("shape:", before.shape)

print('after:')
after = before.reshape((4,2))
print(after)
print("shape:", after.shape)

print('after:')
after = before.reshape((2,2,2))
print(after)
print("shape:", after.shape)

before
[[1 2 3 4]
 [5 6 7 8]]
shape: (2, 4)
after:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
shape: (4, 2)
after:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape: (2, 2, 2)


In [ ]:
print('after:')
after = before.reshape((1,-1))
print(after)
print("shape:", after.shape)

after:
[[1 2 3 4 5 6 7 8]]
shape: (1, 8)


#### .vstack()
`vstack()`

In [ ]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.concatenate((v1,v2),axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.concatenate((v1.reshape((1,4)),v2.reshape((1,4))),axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

#### .hstack()
`hstack()`

In [ ]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [ ]:
np.concatenate((h1,h2),axis=1)

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

#### .resize()
`resize()`

In [ ]:
# Changes to new shape, fills new values with 0
a = np.random.randint(0,11, size=(3,3))
print("before:\n", a)
a.resize((4,4))
print("after:\n", a)

before:
 [[9 4 3]
 [0 3 5]
 [0 2 3]]
after:
 [[9 4 3 0]
 [3 5 0 2]
 [3 0 0 0]
 [0 0 0 0]]


#### .ravel()
`ravel()` returns a contiguous flattened array

In [ ]:
# Flatten an Array
print(a)
a.ravel()

[[9 4 3 0]
 [3 5 0 2]
 [3 0 0 0]
 [0 0 0 0]]


array([9, 4, 3, 0, 3, 5, 0, 2, 3, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
print(a)
a.ravel(order='F')

[[9 4 3 0]
 [3 5 0 2]
 [3 0 0 0]
 [0 0 0 0]]


array([9, 3, 3, 0, 4, 5, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0])

#### .append()
`append()` - Append values to the end of an array.

In [ ]:
a = np.random.randint(1, 10, size=(3,4))
b = np.random.randint(-10, 0, size=(3,4))
print(a)
print(b)
c = np.append(a, b)
c

[[9 2 4 4]
 [4 8 1 2]
 [1 5 8 4]]
[[ -8  -3  -8 -10]
 [-10  -6  -5  -5]
 [ -4  -2  -6  -9]]


array([  9,   2,   4,   4,   4,   8,   1,   2,   1,   5,   8,   4,  -8,
        -3,  -8, -10, -10,  -6,  -5,  -5,  -4,  -2,  -6,  -9])

In [ ]:
print(a)
print(b)
c1 = np.append(a, b, axis=0)
c1

[[9 2 4 4]
 [4 8 1 2]
 [1 5 8 4]]
[[ -8  -3  -8 -10]
 [-10  -6  -5  -5]
 [ -4  -2  -6  -9]]


array([[  9,   2,   4,   4],
       [  4,   8,   1,   2],
       [  1,   5,   8,   4],
       [ -8,  -3,  -8, -10],
       [-10,  -6,  -5,  -5],
       [ -4,  -2,  -6,  -9]])

In [ ]:
print(a)
print(b)
c2 = np.append(a, b, axis=1)
c2

[[9 2 4 4]
 [4 8 1 2]
 [1 5 8 4]]
[[ -8  -3  -8 -10]
 [-10  -6  -5  -5]
 [ -4  -2  -6  -9]]


array([[  9,   2,   4,   4,  -8,  -3,  -8, -10],
       [  4,   8,   1,   2, -10,  -6,  -5,  -5],
       [  1,   5,   8,   4,  -4,  -2,  -6,  -9]])

#### .insert()
`insert()`

In [ ]:
print(a)
a2 = np.insert(a, 1, -5)
a2

[[9 2 4 4]
 [4 8 1 2]
 [1 5 8 4]]


array([ 9, -5,  2,  4,  4,  4,  8,  1,  2,  1,  5,  8,  4])

In [ ]:
print(a)
a2_1 = np.insert(a, 1, -5, axis=0)
a2_1

[[9 2 4 4]
 [4 8 1 2]
 [1 5 8 4]]


array([[ 9,  2,  4,  4],
       [-5, -5, -5, -5],
       [ 4,  8,  1,  2],
       [ 1,  5,  8,  4]])

In [ ]:
print(a)
a2_2 = np.insert(a, 1, -5, axis=1)
a2_2

[[9 2 4 4]
 [4 8 1 2]
 [1 5 8 4]]


array([[ 9, -5,  2,  4,  4],
       [ 4, -5,  8,  1,  2],
       [ 1, -5,  5,  8,  4]])

#### .delete()
`delete()`

In [ ]:
print(b)
b2 = np.delete(b, 0)
b2

[[ -8  -3  -8 -10]
 [-10  -6  -5  -5]
 [ -4  -2  -6  -9]]


array([ -3,  -8, -10, -10,  -6,  -5,  -5,  -4,  -2,  -6,  -9])

In [ ]:
print(b)
b2_1 = np.delete(b, 1, axis=0)
b2_1

[[ -8  -3  -8 -10]
 [-10  -6  -5  -5]
 [ -4  -2  -6  -9]]


array([[ -8,  -3,  -8, -10],
       [ -4,  -2,  -6,  -9]])

In [ ]:
print(b)
b2_2 = np.delete(b, 1, axis=1)
b2_2

[[ -8  -3  -8 -10]
 [-10  -6  -5  -5]
 [ -4  -2  -6  -9]]


array([[ -8,  -8, -10],
       [-10,  -5,  -5],
       [ -4,  -6,  -9]])

In [ ]:
test_array = np.array([1,2,3,4]).reshape((-1,1))
print(test_array)
power_matrix = test_array.copy()
for i in range(2,5):
    power_array = test_array ** i
    power_matrix = np.concatenate((power_matrix,power_array),axis=1)
print(power_matrix)

[[1]
 [2]
 [3]
 [4]]
[[  1   1   1   1]
 [  2   4   8  16]
 [  3   9  27  81]
 [  4  16  64 256]]


## Mathematics

### Operations

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


#### add()
`add()`

In [ ]:
a + 2

array([3, 4, 5, 6])

In [ ]:
np.add(a, 2)

array([3, 4, 5, 6])

#### subtract()
`subtract()`

In [ ]:
a - 2

array([-1,  0,  1,  2])

In [ ]:
np.subtract(a, 2)

array([-1,  0,  1,  2])

#### multiply()
`multiply()`

In [ ]:
a * 2

array([2, 4, 6, 8])

In [ ]:
np.multiply(a, 2)

array([2, 4, 6, 8])

#### divide()
`divide()`

In [ ]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
np.divide(a, 2)

array([0.5, 1. , 1.5, 2. ])

#### power()
`power()`

In [ ]:
a ** 2

array([ 1,  4,  9, 16])

In [ ]:
np.power(a, 2)

array([ 1,  4,  9, 16], dtype=int32)

#### sin()
`sin()`

In [ ]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

#### exp()
`exp()`

In [ ]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

#### other

In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

In [ ]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [ ]:
c = np.array([-1, -2])
# a + c

Broadcasting - https://numpy.org/doc/stable/user/basics.broadcasting.html

### Linear Algebra

#### Transpose
`.T`

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [ ]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
a.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

#### dot()
`dot()`

In [ ]:
a = np.array([1,2,3])
b = np.array([3,-1,-2])

print(1*3 + 2*(-1) + 3*(-2))
np.dot(a,b)

-5


-5

In [ ]:
a * b

array([ 3, -2, -6])

In [ ]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [3, 2]])
np.dot(a, b)

array([[4, 1],
       [3, 2]])

In [ ]:
np.matmul(a,b)

array([[4, 1],
       [3, 2]])

#### matmul()
`matmul()`

https://en.wikipedia.org/wiki/Matrix_multiplication

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,4), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [ ]:
np.matmul(a,b)

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.]])

#### linalg
`linalg`

In [ ]:
# Find the determinant
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [ ]:
A = np.array([[1., 2.], [3., 4.]])
A_inv = np.linalg.inv(A)
print(A_inv)
np.matmul(A, A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [ ]:
bad_matrix = np.zeros((2,2))
# np.linalg.inv(bad_matrix)

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

### Aggregate Operations

In [ ]:
stats = np.array([[0,1,2,3],[4,-1,5,6]])
stats

array([[ 0,  1,  2,  3],
       [ 4, -1,  5,  6]])

#### min()
`min()`

In [ ]:
np.min(stats)

-1

#### max()
`max()`

In [ ]:
np.max(stats)

6

In [ ]:
np.max(stats, axis=1)

array([3, 6])

In [ ]:
np.max(stats, axis=0)

array([4, 1, 5, 6])

#### sum()
`sum()`

In [ ]:
np.sum(stats)

20

In [ ]:
np.sum(stats, axis=0)

array([4, 0, 7, 9])

In [ ]:
np.sum(stats, axis=1)

array([ 6, 14])

#### [mean()](https://numpy.org/doc/stable/reference/generated/numpy.mean.html)
`mean()`

In [ ]:
np.mean(stats)

2.5

#### std()
`std()`

In [ ]:
np.std(stats)

2.29128784747792

In [ ]:
np.round(np.std(stats),3)

2.291

In [ ]:
arr1 = np.array([-1,0,1])
arr2 = np.array([-5,0,5])

In [ ]:
np.mean(arr1), np.mean(arr2)

(0.0, 0.0)

In [ ]:
np.std(arr1), np.std(arr2)

(0.816496580927726, 4.08248290463863)

#### median()
`median()`

In [ ]:
np.median(stats)

2.5

#### [corrcoef()](https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html)
`corrcoef()`

In [ ]:
x = np.random.normal(10, 5, size=20)
y = x * .5 + np.random.normal(size=20)
print(x)
print(y)
np.corrcoef(x,y)

[10.77473713 11.8908126   5.56107126  0.09601766  8.26043925 10.78174485
 16.1514534  16.01189924  8.06336591  8.48848625  4.75723517  2.89991031
  1.46864905 19.75387698  7.45173909  7.80962849  3.7360232  13.88745178
  1.93051076  8.9362986 ]
[ 4.491902    6.3323088   2.26973049 -1.13262335  4.1020374   5.81920429
  8.14224392  8.30842152  3.39736086  3.88150196  1.70615714  1.090402
 -0.07882176  8.15065589  3.90329569  3.50303331  0.23781325  7.40650815
  0.05795702  4.5200947 ]


array([[1.        , 0.97743006],
       [0.97743006, 1.        ]])

### Boolean Algebra

#### and

In [ ]:
np.logical_and(True, False)

False

#### or

In [ ]:
np.logical_or(True, True)

True

#### not

In [ ]:
np.logical_not(True), np.logical_not(5==3)

(False, True)

## Miscellaneous

### Load Data from File
* [genfromtxt()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.genfromtxt.html) - Load data from a text file, with missing values handled as specified.
* [loadtxt()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.loadtxt.html) - Load data from a text file. Each row in the text file must have the same number of values.

#### txt

In [1]:
txt_data = np.genfromtxt('numpy_data.txt', delimiter=';')
txt_data = txt_data.astype('int32')
print(txt_data)

NameError: ignored

In [ ]:
txt_data = np.genfromtxt('numpy_data.txt', delimiter='\n')
# txt_data = txt_data.astype('int32')
print(txt_data)

#### csv - comma separated values

In [ ]:
csv_data = np.genfromtxt('numpy_data.csv', delimiter=',')
csv_data = csv_data.astype('int32')
print(csv_data)

In [ ]:
print(csv_data.T)

#### npy

### Saving (Dumping) Data to File
* [savetxt](https://docs.scipy.org/doc/numpy/reference/generated/numpy.savetxt.html) - Save an array to a text file.

#### csv

In [ ]:
csv_save = np.asarray([ [1,2,3], [4,5,6], [7,8,9] ])
print(csv_save)
np.savetxt('stats_data.csv',
           csv_save,
           delimiter=',',
           fmt='%.2f'
          )

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### npy

### Boolean Masking and Advanced Indexing

In [ ]:
rdata = np.random.randint(-5, 5, size=20)

In [ ]:
print(rdata)
rdata >= 2, rdata

[-4 -1  1  3 -3 -2 -5 -5  1 -5  1 -2 -2  3  3  3 -3 -2 -3 -5]


(array([False, False, False,  True, False, False, False, False, False,
        False, False, False, False,  True,  True,  True, False, False,
        False, False]),
 array([-4, -1,  1,  3, -3, -2, -5, -5,  1, -5,  1, -2, -2,  3,  3,  3, -3,
        -2, -3, -5]))

In [ ]:
(~((rdata > -1) & (rdata < 3)))

array([ True,  True, False,  True,  True,  True,  True,  True, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [ ]:
rdata > 2

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False,  True,  True,  True, False, False,
       False, False])

In [ ]:
rdata[rdata > 2]

array([3, 3, 3, 3])

### NaN

In [ ]:
None

In [ ]:
a = np.array([1,2,None,4])

In [ ]:
a[2]

In [ ]:
np.nan

nan

In [ ]:
b = np.array([
    [np.nan,2,3],
    [4, np.nan, 9],
    [10,20,40],
    [np.nan, np.nan,-1],
    [1,2,3]
])

In [ ]:
b

array([[nan,  2.,  3.],
       [ 4., nan,  9.],
       [10., 20., 40.],
       [nan, nan, -1.],
       [ 1.,  2.,  3.]])

In [ ]:
np.isnan(b[:,0])

array([ True, False, False,  True, False])

In [ ]:
b[np.isnan(b[:,0]),:]

array([[nan,  2.,  3.],
       [nan, nan, -1.]])

In [ ]:
b[~np.isnan(b[:,0]),:]

array([[ 4., nan,  9.],
       [10., 20., 40.],
       [ 1.,  2.,  3.]])

## Exercises

### Reverse Identity Matrix

In [ ]:
ident = np.identity(6)

In [ ]:
ident

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
ident[::-1,::-1]


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
arr = np.identity(5, int)
arr_flip = arr[::-1]
print(arr)
print(arr_flip)


[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]]


In [ ]:
a = np.eye(4)
np.flip(a, axis = 0)


array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

### Chessboard

0 - black

1 - white

In [ ]:
chess_board_manual = np.array(
    [
    [1, 0, 1, 0, 1, 0, 1, 0],    # 1 = White
    [0, 1, 0, 1, 0, 1, 0, 1],    # 0 = Black
    [1, 0, 1, 0, 1, 0, 1, 0],
    [0, 1, 0, 1, 0, 1, 0, 1],
    [1, 0, 1, 0, 1, 0, 1, 0],
    [0, 1, 0, 1, 0, 1, 0, 1],
    [1, 0, 1, 0, 1, 0, 1, 0],
    [0, 1, 0, 1, 0, 1, 0, 1]
    ]
)
chess_board_manual

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [ ]:
def board(n):
    print ("board 8x8")
    x = np.zeros((n, n), dtype = int)
    x[1::2, ::2] = 1
    x[::2, 1::2] = 1
    for i in range (n):
        for j in range (n):
            print (x[i][j], end = " ")
        print()
n = 8
board(n)


board 8x8
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 


In [ ]:
chess = [[(x+y)%2 for x in range(8)] for y in range(8)]
chess

[[0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0]]

In [ ]:
r1 = np.ones((1,8), dtype='int32')
r2 = np.zeros((1,8), dtype='int32')
r1[0, 1::2] = 0
r2[0, 1::2] = 1
# print(r1)
# print(r2)
np.vstack((r1,r2,r1,r2,r1,r2,r1,r2))


array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [ ]:
chess = np.zeros((8,8))
chess[::2, 1::2]=1
chess[1::2, ::2]=1
chess

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [ ]:
a = np.zeros((64))
a[::2] = 1
a.reshape(8,8)


array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])