# [NumPy](https://numpy.org/) Tutorial
**NumPy**'s main object is the **homogeneous** multidimensional array. It is a table of elements (usually numbers), all of the **same type**, indexed by a tuple of non-negative integers.

Cheat Sheets:
* [by DataCamp](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)
* [by DataQuest](https://s3.amazonaws.com/dq-blog-files/numpy-cheat-sheet.pdf)

## Load the package

In [1]:
import numpy as np
# alias

### Version
`__version__`

**dunder** - Double Underscore

In [2]:
print(np.__version__)

1.22.1


## Array
NumPy provides an N-dimensional array type, the `ndarray`, which describes a collection of "items" of the same type. The items can be indexed using for example N integers.

### Basics
[np.array()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html)

In [3]:
a = np.array([1,2,3,4,5,6])
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [4]:
[1,2,3]

[1, 2, 3]

In [5]:
np.array([1,2,3])

array([1, 2, 3])

In [6]:
# Ask for Help
# np.info(np.array)

#### Inspecting

In [7]:
# Get Dimension
a.ndim

1

In [8]:
# Get Type
a.dtype

dtype('int32')

In [9]:
a.astype('float')

array([1., 2., 3., 4., 5., 6.])

In [10]:
# Get number of elements
a.size

6

In [11]:
# Get Size
a.itemsize

4

In [12]:
# Get total size
a.nbytes

24

In [13]:
a.shape

(6,)

In [14]:
st_array = np.array(['a', 'b'])

In [15]:
''.join(st_array.tolist())

'ab'

### Array Shapes
<img src="numpy-1d2d3d-array.png" style="height:300px">

In [16]:
b = np.array([
    [9.0,8.0,7.0],
    [6.0,5.0,4.0]
])
print(b)
print(type(b))

[[9. 8. 7.]
 [6. 5. 4.]]
<class 'numpy.ndarray'>


In [17]:
# Get Shape
b.shape

(2, 3)

In [18]:
b.size

6

In [19]:
c = np.array([
    [
        [1,2,3],
        [5,3,4]
    ],
    [
        [1,5,6],
        [5,7,8]]
    ]
)
print(c)
print(type(c))

[[[1 2 3]
  [5 3 4]]

 [[1 5 6]
  [5 7 8]]]
<class 'numpy.ndarray'>


In [20]:
c.shape

(2, 2, 3)

In [21]:
c.size

12

### Special Arrays

#### zeros()
`zeros()`

In [22]:
# All 0s matrix
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### ones()
`ones()`

In [23]:
# All 1s matrix
np.ones((3,2,4), dtype='int32')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

#### identity()
`identity()`

In [24]:
# The identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### full()
`full()`

In [25]:
# Any other number
np.full((3,4), 81)

array([[81, 81, 81, 81],
       [81, 81, 81, 81],
       [81, 81, 81, 81]])

In [26]:
print(a)
np.full(a.shape, 5)

[1 2 3 4 5 6]


array([5, 5, 5, 5, 5, 5])

#### full_like()
`full_like()`

In [27]:
# Any other number (full_like)
print(a)
np.full_like(a, 5)

[1 2 3 4 5 6]


array([5, 5, 5, 5, 5, 5])

#### repeat()
`repeat()`

In [28]:
# Repeat an array
arr = np.array([
    [1,2,3]
])
print(arr.shape)
r1 = np.repeat(arr, 5, axis=0)
print(r1)

(1, 3)
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [29]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


#### linspace()
`linspace()`

In [30]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [31]:
np.linspace(0,100,11)[1:-1]

array([10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [32]:
np.linspace(0,100,10,endpoint=False)

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [33]:
np.linspace(0,100,10,endpoint=False)[1:]

array([10., 20., 30., 40., 50., 60., 70., 80., 90.])

#### arange()
Like the standard **Python** function `range()`, **NumPy** has a similar function called `arange()`

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [36]:
np.arange(0,10,3)

array([0, 3, 6, 9])

### Randomization

In [37]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.61743179, 0.21503872],
       [0.819412  , 0.53945388],
       [0.99674882, 0.08164335],
       [0.64513985, 0.3902395 ]])

In [38]:
np.random.rand(4,2)

array([[0.5511289 , 0.42018567],
       [0.7825552 , 0.75767302],
       [0.73110871, 0.34049784],
       [0.7928445 , 0.95137366]])

In [39]:
np.random.seed(0)
np.random.rand(4,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

In [40]:
np.random.seed(0)
np.random.rand(4,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

In [41]:
# Random Integer values
np.random.seed(0)
np.random.randint(-4,8, size=(5,5))

array([[ 1, -4, -1,  7, -1],
       [ 3,  5, -1,  1, -2],
       [ 0,  3,  2,  4,  4],
       [ 6, -3,  2,  3,  3],
       [ 4, -3,  1,  5,  4]])

### Copying Arrays

In [42]:
a = np.array([1,2,3])
b = a.copy()
c = a

print("before:")
print("a", a)
print("b", b)
print("c", c)

b[0] = 100
print("after b:")
print("a", a)
print("b", b)
print("c", c)

c[0] = 10

print("after c:")
print("a", a)
print("b", b)
print("c", c)

before:
a [1 2 3]
b [1 2 3]
c [1 2 3]
after b:
a [1 2 3]
b [100   2   3]
c [1 2 3]
after c:
a [10  2  3]
b [100   2   3]
c [10  2  3]


#### .tolist()
`tolist()`

In [43]:
print(c)
type(c.tolist())

[10  2  3]


list

## Accessing/Changing specific elements, rows, columns, etc

### Accessing

In [44]:
l = [1,2,3,4,5]
l[1:-1]

[2, 3, 4]

In [45]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [46]:
# Get a specific element [r, c]
a[1, 5]

13

In [47]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [48]:
a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [49]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [50]:
print(a)
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


array([2, 4, 6])

### Changing

In [51]:
print("before:\n", a)
a[1,5] = 20
print("after:\n", a)

before:
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
after:
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [52]:
print("before:\n", a)
a[:,3] = 3
print("after:\n", a)

before:
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
after:
 [[ 1  2  3  3  5  6  7]
 [ 8  9 10  3 12 20 14]]


In [53]:
print("before:\n", a)
a[:,2] = [1000,2000]
print("after:\n", a)

before:
 [[ 1  2  3  3  5  6  7]
 [ 8  9 10  3 12 20 14]]
after:
 [[   1    2 1000    3    5    6    7]
 [   8    9 2000    3   12   20   14]]


*3-d example

In [54]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
print("shape:", b.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape: (2, 2, 2)


In [55]:
# Get specific element (work outside in)
b[0,1,1]

4

In [56]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [57]:
# replace
print("before:\n", b)
b[:,1,:] = [[9,9],[8,8]]
print("after:\n", b)

before:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
after:
 [[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [58]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

#### Example
Create 5x5 Array with 1s on border, 0s inside and 9 in the center
```python
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
```

In [59]:
list1 = [12,3,4]

In [60]:
list1[0] = -7

In [61]:
list1

[-7, 3, 4]

In [62]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Reorganizing Arrays

#### .reshape()
`reshape()`

In [63]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print("before")
print(before)
print("shape:", before.shape)

print('after:')
after = before.reshape((4,2))
print(after)
print("shape:", after.shape)

print('after:')
after = before.reshape((2,2,2))
print(after)
print("shape:", after.shape)

before
[[1 2 3 4]
 [5 6 7 8]]
shape: (2, 4)
after:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
shape: (4, 2)
after:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape: (2, 2, 2)


In [64]:
print('after:')
after = before.reshape((1,-1))
print(after)
print("shape:", after.shape)

after:
[[1 2 3 4 5 6 7 8]]
shape: (1, 8)


#### .vstack()
`vstack()`

In [65]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
np.concatenate((v1,v2),axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [67]:
np.concatenate((v1.reshape((1,4)),v2.reshape((1,4))),axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

#### .hstack()
`hstack()`

In [68]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [69]:
np.concatenate((h1,h2),axis=1)

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

#### .resize()
`resize()`

In [70]:
# Changes to new shape, fills new values with 0
a = np.random.randint(0,11, size=(3,3))
print("before:\n", a)
a.resize((4,4))
print("after:\n", a)

before:
 [[9 4 3]
 [0 3 5]
 [0 2 3]]
after:
 [[9 4 3 0]
 [3 5 0 2]
 [3 0 0 0]
 [0 0 0 0]]


#### .ravel()
`ravel()` returns a contiguous flattened array

In [71]:
# Flatten an Array
print(a)
a.ravel()

[[9 4 3 0]
 [3 5 0 2]
 [3 0 0 0]
 [0 0 0 0]]


array([9, 4, 3, 0, 3, 5, 0, 2, 3, 0, 0, 0, 0, 0, 0, 0])

In [72]:
print(a)
a.ravel(order='F')

[[9 4 3 0]
 [3 5 0 2]
 [3 0 0 0]
 [0 0 0 0]]


array([9, 3, 3, 0, 4, 5, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0])

#### .append()
`append()` - Append values to the end of an array.

In [73]:
a = np.random.randint(1, 10, size=(3,4))
b = np.random.randint(-10, 0, size=(3,4))
print(a)
print(b)
c = np.append(a, b)
c

[[9 2 4 4]
 [4 8 1 2]
 [1 5 8 4]]
[[ -8  -3  -8 -10]
 [-10  -6  -5  -5]
 [ -4  -2  -6  -9]]


array([  9,   2,   4,   4,   4,   8,   1,   2,   1,   5,   8,   4,  -8,
        -3,  -8, -10, -10,  -6,  -5,  -5,  -4,  -2,  -6,  -9])

In [74]:
print(a)
print(b)
c1 = np.append(a, b, axis=0)
c1

[[9 2 4 4]
 [4 8 1 2]
 [1 5 8 4]]
[[ -8  -3  -8 -10]
 [-10  -6  -5  -5]
 [ -4  -2  -6  -9]]


array([[  9,   2,   4,   4],
       [  4,   8,   1,   2],
       [  1,   5,   8,   4],
       [ -8,  -3,  -8, -10],
       [-10,  -6,  -5,  -5],
       [ -4,  -2,  -6,  -9]])

In [75]:
print(a)
print(b)
c2 = np.append(a, b, axis=1)
c2

[[9 2 4 4]
 [4 8 1 2]
 [1 5 8 4]]
[[ -8  -3  -8 -10]
 [-10  -6  -5  -5]
 [ -4  -2  -6  -9]]


array([[  9,   2,   4,   4,  -8,  -3,  -8, -10],
       [  4,   8,   1,   2, -10,  -6,  -5,  -5],
       [  1,   5,   8,   4,  -4,  -2,  -6,  -9]])

#### .insert()
`insert()`

In [76]:
print(a)
a2 = np.insert(a, 1, -5)
a2

[[9 2 4 4]
 [4 8 1 2]
 [1 5 8 4]]


array([ 9, -5,  2,  4,  4,  4,  8,  1,  2,  1,  5,  8,  4])

In [77]:
print(a)
a2_1 = np.insert(a, 1, -5, axis=0)
a2_1

[[9 2 4 4]
 [4 8 1 2]
 [1 5 8 4]]


array([[ 9,  2,  4,  4],
       [-5, -5, -5, -5],
       [ 4,  8,  1,  2],
       [ 1,  5,  8,  4]])

In [78]:
print(a)
a2_2 = np.insert(a, 1, -5, axis=1)
a2_2

[[9 2 4 4]
 [4 8 1 2]
 [1 5 8 4]]


array([[ 9, -5,  2,  4,  4],
       [ 4, -5,  8,  1,  2],
       [ 1, -5,  5,  8,  4]])

#### .delete()
`delete()`

In [79]:
print(b)
b2 = np.delete(b, 0)
b2

[[ -8  -3  -8 -10]
 [-10  -6  -5  -5]
 [ -4  -2  -6  -9]]


array([ -3,  -8, -10, -10,  -6,  -5,  -5,  -4,  -2,  -6,  -9])

In [80]:
print(b)
b2_1 = np.delete(b, 1, axis=0)
b2_1

[[ -8  -3  -8 -10]
 [-10  -6  -5  -5]
 [ -4  -2  -6  -9]]


array([[ -8,  -3,  -8, -10],
       [ -4,  -2,  -6,  -9]])

In [81]:
print(b)
b2_2 = np.delete(b, 1, axis=1)
b2_2

[[ -8  -3  -8 -10]
 [-10  -6  -5  -5]
 [ -4  -2  -6  -9]]


array([[ -8,  -8, -10],
       [-10,  -5,  -5],
       [ -4,  -6,  -9]])

In [82]:
test_array = np.array([1,2,3,4]).reshape((-1,1))
print(test_array)
power_matrix = test_array.copy()
for i in range(2,5):
    power_array = test_array ** i
    power_matrix = np.concatenate((power_matrix,power_array),axis=1)
print(power_matrix)

[[1]
 [2]
 [3]
 [4]]
[[  1   1   1   1]
 [  2   4   8  16]
 [  3   9  27  81]
 [  4  16  64 256]]
